### PR TITLE
Fixed update.sh and updated

### PR DESCRIPTION
**Pull request by yasinuslu**
I fixed update.sh and updated the package with bootstrap master. I haven't tested the package though.

### CODE REVIEW

**Comment by mizzao** [comment]
I cherry-picked the one commit you made to 7c0d861a726ccf89ed1509dc2f122ba5cf30b252. Makes the history a bit cleaner.

I don't understand exactly what all the changes are from, though. Is that a new version of BS3, or is it just whatever happened to be in the git repo at the time you ran `update.sh`?

I think this package should generally just follow the BS3 releases, and not any of the in-between stuff unless there are serious issues.

**EDIT**: I just kept the changes to `update.sh` for now. That guy just wanted it to work, but we don't need to keep a random BS3 commit in the repo for now.

**Comment by yasinuslu** [comment]
No problem, i just responded to @ssteinerx's request to make it work :)

Yes, script just makes a git pull and builds bootstrap. We might tinker it to get releases but `update.sh` isn't that necessary anymore. Bootstrap was at version 2 when we created this package so we were following master branch and it weren't stable, we needed to update it frequently. One day i got sick of building it manually and wrote a script :)

**Comment by mizzao** [comment]
Script is still pretty useful; I added an argument to pull a tag and used it to build v3.3.0 :)

**Comment by yasinuslu** [comment]
@mizzao Glad it became useful for you :)

**Pull request closed without merging**
